<?php
require_once dirname(__FILE__) . '/includes/init.php';
$pageTitle = 'תשובות לסקר שביעות רצון';
$admin_nav_context = 'satisfaction_survey';
global $conn;

$featureLabels = ['transactions'=>'הוספת פעולות','reports'=>'דוחות ותובנות','budgets'=>'תקציבים ויעדים','shopping'=>'רשימת קניות','work'=>'סידור עבודה','ai'=>'התזרים החכם'];
$summary = ['count'=>0,'csat'=>0.0,'nps'=>0.0,'routine'=>0.0];
$summaryRes = $conn->query('SELECT COUNT(*) c, COALESCE(AVG(csat),0) csat, COALESCE(AVG(nps),0) nps, COALESCE(AVG(routine_score),0) routine FROM satisfaction_survey_responses');
if ($summaryRes) {$summary = array_merge($summary, $summaryRes->fetch_assoc() ?: []);}
$rows=[];
$sql="SELECT s.*,u.first_name,u.last_name,u.email,h.name home_name FROM satisfaction_survey_responses s INNER JOIN users u ON u.id=s.user_id LEFT JOIN homes h ON h.id=u.home_id ORDER BY s.submitted_at DESC,s.id DESC";
$res=$conn->query($sql);if($res){while($row=$res->fetch_assoc())$rows[]=$row;}
function svh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function svStars($value){$out='';for($i=1;$i<=5;$i++)$out.='<span class="'.($i<=$value?'on':'').'">★</span>';return $out;}
require dirname(__FILE__) . '/includes/partials/head.php';
require dirname(__FILE__) . '/includes/partials/layout_shell_start.php';
?>
<style>
.sv-hero{background:linear-gradient(135deg,#17253a,#254668);border-radius:24px;padding:28px;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.sv-hero h1{font-size:1.65rem;font-weight:800;margin:4px 0}.sv-hero p{color:#ced9e7}.sv-hero__icon{width:72px;height:72px;border-radius:22px;background:rgba(255,255,255,.11);display:grid;place-items:center;font-size:2rem}.sv-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:22px}.sv-kpi{background:#fff;border:1px solid #eef1f5;border-radius:18px;padding:18px;box-shadow:0 8px 25px rgba(37,50,70,.05)}.sv-kpi small{display:block;color:#7a8798;font-weight:700}.sv-kpi strong{display:block;color:#243348;font-size:1.8rem;margin-top:5px}.sv-kpi strong span{font-size:.85rem;color:#9aa4b2}.sv-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sv-card{background:#fff;border:1px solid #e9edf2;border-radius:20px;padding:20px;box-shadow:0 8px 24px rgba(37,50,70,.05)}.sv-user{display:flex;align-items:center;gap:12px;padding-bottom:15px;border-bottom:1px solid #edf0f4}.sv-avatar{width:46px;height:46px;border-radius:15px;background:#e9f8f0;color:#168750;display:grid;place-items:center;font-weight:900}.sv-user h2{font-size:1rem;font-weight:800;color:#263349}.sv-user p{font-size:.8rem;color:#8290a2}.sv-time{margin-right:auto;font-size:.75rem;color:#96a0ad}.sv-ratings{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.sv-rating{background:#f7f9fc;border-radius:13px;padding:10px;text-align:center}.sv-rating small{display:block;color:#758195;font-weight:700}.sv-rating b{font-size:1.2rem;color:#27364b}.sv-stars{direction:ltr;white-space:nowrap;font-size:.72rem;color:#dde3ea}.sv-stars .on{color:#f5b73b}.sv-feature{display:inline-flex;align-items:center;gap:8px;border-radius:999px;background:#eef4ff;color:#365eab;padding:7px 11px;font-size:.82rem;font-weight:800}.sv-feedback{margin-top:13px;background:#f8fafc;border-right:4px solid #29b669;border-radius:12px;padding:12px;color:#49566a;line-height:1.6;white-space:pre-wrap}.sv-empty{text-align:center;background:#fff;border-radius:20px;padding:55px;color:#8793a4}@media(max-width:900px){.sv-kpis{grid-template-columns:repeat(2,1fr)}.sv-grid{grid-template-columns:1fr}}@media(max-width:520px){.sv-hero{padding:20px}.sv-hero__icon{display:none}.sv-kpis{gap:9px}.sv-kpi{padding:13px}.sv-ratings{grid-template-columns:1fr}.sv-user{align-items:flex-start}.sv-time{display:none}}
</style>
<main class="admin-page-main w-full min-w-0 max-w-full">
<section class="sv-hero"><div><p class="text-sm font-bold text-emerald-300">קול המשתמשים</p><h1>סקר שביעות רצון</h1><p>כל התשובות, הציונים והפידבק הפתוח במקום אחד.</p></div><div class="sv-hero__icon"><i class="fa-solid fa-heart"></i></div></section>
<section class="sv-kpis"><article class="sv-kpi"><small>תשובות</small><strong><?php echo number_format((int)$summary['count']);?></strong></article><article class="sv-kpi"><small>שביעות רצון ממוצעת</small><strong><?php echo number_format((float)$summary['csat'],1);?> <span>/ 5</span></strong></article><article class="sv-kpi"><small>המלצה ממוצעת</small><strong><?php echo number_format((float)$summary['nps'],1);?> <span>/ 5</span></strong></article><article class="sv-kpi"><small>שגרה ממוצעת</small><strong><?php echo number_format((float)$summary['routine'],1);?> <span>/ 5</span></strong></article></section>
<?php if(!$rows):?><div class="sv-empty"><i class="fa-regular fa-message text-4xl mb-3"></i><h2 class="font-bold text-lg">עוד אין תשובות</h2><p>ברגע שמשתמשים ישלחו את הסקר, התשובות יופיעו כאן.</p></div><?php else:?><section class="sv-grid"><?php foreach($rows as $r):$name=trim(($r['first_name']??'').' '.($r['last_name']??''));?><article class="sv-card"><header class="sv-user"><div class="sv-avatar"><?php echo svh(mb_substr($name?:'מ',0,1,'UTF-8'));?></div><div><h2><?php echo svh($name?:'משתמש');?></h2><p><?php echo svh($r['email']??'');?><?php if(!empty($r['home_name'])):?> · <?php echo svh($r['home_name']);?><?php endif;?></p></div><time class="sv-time" datetime="<?php echo svh($r['submitted_at']);?>"><?php echo svh(date('d.m.Y H:i',strtotime($r['submitted_at'])));?></time></header><div class="sv-ratings"><?php foreach([['csat','שביעות רצון'],['nps','המלצה'],['routine_score','חלק מהשגרה']] as $m):$v=(int)$r[$m[0]];?><div class="sv-rating"><small><?php echo $m[1];?></small><b><?php echo $v;?>/5</b><div class="sv-stars"><?php echo svStars($v);?></div></div><?php endforeach;?></div><div class="sv-feature"><i class="fa-solid fa-bolt"></i><?php echo svh($featureLabels[$r['most_used_feature']]??$r['most_used_feature']);?></div><div class="sv-feedback"><?php echo $r['feedback']!==''?svh($r['feedback']):'<span style="color:#9ba5b2">לא נכתב פידבק פתוח</span>';?></div></article><?php endforeach;?></section><?php endif;?>
</main>
<?php require dirname(__FILE__) . '/includes/partials/layout_shell_end.php';require dirname(__FILE__) . '/includes/partials/footer.php';?>
