<?php
require_once('../path.php');
include(ROOT_PATH . '/app/database/db.php');
include(ROOT_PATH . '/assets/includes/auth_check.php');
require_once ROOT_PATH . '/app/functions/payment_methods.php';
$home_id=(int)$_SESSION['home_id'];
$home_data=selectOne('homes',['id'=>$home_id]) ?: ['name'=>''];
$payment_methods=tazrim_payment_methods($home_id,true);
$categories=[];$r=mysqli_query($conn,"SELECT id,name,type,icon FROM categories WHERE home_id=$home_id AND is_active=1 ORDER BY type,name");while($x=mysqli_fetch_assoc($r))$categories[]=$x; $house_users=[];$r=mysqli_query($conn,"SELECT id,first_name FROM users WHERE home_id=$home_id ORDER BY first_name");while($x=mysqli_fetch_assoc($r))$house_users[]=$x;
$type=in_array($_GET['type']??'', ['income','expense'],true)?$_GET['type']:'';
$payment_id=max(0,(int)($_GET['payment_method_id']??0));
$category_id=max(0,(int)($_GET['category_id']??0));
$date_from=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['date_from']??'')?$_GET['date_from']:'';
$date_to=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['date_to']??'')?$_GET['date_to']:'';
$amount_min=is_numeric($_GET['amount_min']??null)?max(0,(float)$_GET['amount_min']):null;
$amount_max=is_numeric($_GET['amount_max']??null)?max(0,(float)$_GET['amount_max']):null;
$q=trim((string)($_GET['q']??''));
$user_id=max(0,(int)($_GET['user_id']??0));
$month=preg_match('/^\d{4}-\d{2}$/',$_GET['month']??'')?$_GET['month']:'';
$payment_type=in_array($_GET['payment_type']??'',array_keys(tazrim_payment_method_types()),true)?$_GET['payment_type']:'';
$where=["t.home_id=$home_id"];
if($type)$where[]="t.type='".mysqli_real_escape_string($conn,$type)."'";
if($payment_id)$where[]="t.payment_method_id=$payment_id";
if($category_id)$where[]="t.category=$category_id";
if($date_from)$where[]="t.transaction_date>='".mysqli_real_escape_string($conn,$date_from)."'";
if($date_to)$where[]="t.transaction_date<='".mysqli_real_escape_string($conn,$date_to)."'";
if($amount_min!==null)$where[]='t.amount>='.sprintf('%.2F',$amount_min);
if($amount_max!==null)$where[]='t.amount<='.sprintf('%.2F',$amount_max);
if($q!=='')$where[]="t.description LIKE '%".mysqli_real_escape_string($conn,$q)."%'";
if($user_id)$where[]="t.user_id=$user_id";
if($month)$where[]="DATE_FORMAT(t.transaction_date,'%Y-%m')='".mysqli_real_escape_string($conn,$month)."'";
if($payment_type)$where[]="pm.type='".mysqli_real_escape_string($conn,$payment_type)."'";
$sql="SELECT t.*,c.name category_name,c.icon cat_icon,u.first_name user_name,pm.name payment_name,pm.type payment_type FROM transactions t LEFT JOIN categories c ON c.id=t.category LEFT JOIN users u ON u.id=t.user_id LEFT JOIN payment_methods pm ON pm.id=t.payment_method_id WHERE ".implode(' AND ',$where)." ORDER BY t.transaction_date DESC,t.created_at DESC";
$res=mysqli_query($conn,$sql);$rows=[];$income=0;$expense=0;while($row=mysqli_fetch_assoc($res)){ $rows[]=$row;if($row['type']==='income')$income+=(float)$row['amount'];else $expense+=(float)$row['amount']; }
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function chosen_name($items,$id,$fallback){foreach($items as $x)if((int)$x['id']===$id)return $x['name'];return $fallback;}
?>
<!DOCTYPE html><html lang="he" dir="rtl"><head><?php include(ROOT_PATH.'/assets/includes/setup_meta_data.php');?><title>כל הפעולות | התזרים</title></head><body class="bg-gray"><div class="dashboard-container"><?php include(ROOT_PATH.'/assets/includes/sidebar_bavbar.php');?><?php include(ROOT_PATH.'/assets/includes/banner_alert.php');?><div class="content-wrapper all-transactions-page">
<div class="all-transactions-title"><div><h1 class="section-title">כל הפעולות</h1><p>היסטוריית הפעולות המלאה של הבית</p></div><div class="all-page-actions"><button type="button" class="transactions-all-link" onclick="openAllFilters()"><i class="fa-solid fa-filter"></i>פילטרים</button><a class="transactions-all-link all-excel-link" href="<?php echo BASE_URL;?>app/ajax/export_transactions_excel.php?<?php echo h(http_build_query(['start_date'=>$date_from?:'2000-01-01','end_date'=>$date_to?:date('Y-m-d'),'scope'=>$type?:'all','user_id'=>$user_id?:'','min_amount'=>$amount_min,'max_amount'=>$amount_max,'search_text'=>$q,'category_ids'=>$category_id?[$category_id]:[],'payment_method_id'=>$payment_id?:'','payment_type'=>$payment_type,'month'=>$month]));?>"><i class="fa-solid fa-file-excel"></i>ייצוא לאקסל</a><a href="<?php echo BASE_URL;?>index.php" class="transactions-all-link"><i class="fa-solid fa-arrow-right"></i>חזרה לראשי</a></div></div>
<div id="all-filters-modal" class="modal"><div class="modal-content all-filters-modal__content"><div class="modal-header"><h3><i class="fa-solid fa-filter"></i> סינון פעולות</h3><button type="button" class="close-modal-btn" onclick="closeAllFilters()" aria-label="סגור"><i class="fa-solid fa-xmark"></i></button></div><div class="modal-body"><form class="all-filters" method="get" id="all-filters-form">
<div class="all-filter-search"><i class="fa-solid fa-magnifying-glass"></i><input type="search" name="q" value="<?php echo h($q);?>" placeholder="חיפוש לפי תיאור"></div>
<div class="all-filter-grid">
<div class="all-filter"><label>סוג פעולה</label><details class="filter-picker"><summary><span><?php echo $type==='income'?'הכנסות':($type==='expense'?'הוצאות':'הכול');?></span><i class="fa-solid fa-chevron-down"></i></summary><div class="filter-picker__menu"><button type="button" data-name="type" data-value="">הכול</button><button type="button" data-name="type" data-value="expense">הוצאות</button><button type="button" data-name="type" data-value="income">הכנסות</button></div></details><input type="hidden" name="type" value="<?php echo h($type);?>"></div>
<div class="all-filter"><label>אמצעי תשלום</label><details class="filter-picker"><summary><span><?php echo h(chosen_name($payment_methods,$payment_id,'הכול'));?></span><i class="fa-solid fa-chevron-down"></i></summary><div class="filter-picker__menu"><button type="button" data-name="payment_method_id" data-value="">הכול</button><?php foreach($payment_methods as $pm):?><button type="button" data-name="payment_method_id" data-value="<?php echo (int)$pm['id'];?>"><?php echo h(tazrim_payment_method_public_name($pm));?></button><?php endforeach;?></div></details><input type="hidden" name="payment_method_id" value="<?php echo $payment_id?:'';?>"></div>
<div class="all-filter"><label>קטגוריה</label><details class="filter-picker"><summary><span><?php echo h(chosen_name($categories,$category_id,'הכול'));?></span><i class="fa-solid fa-chevron-down"></i></summary><div class="filter-picker__menu"><button type="button" data-name="category_id" data-value="">הכול</button><?php foreach($categories as $c):?><button type="button" data-name="category_id" data-value="<?php echo (int)$c['id'];?>"><?php echo h($c['name']);?></button><?php endforeach;?></div></details><input type="hidden" name="category_id" value="<?php echo $category_id?:'';?>"></div>
<div class="all-filter"><label>מתאריך</label><input type="date" name="date_from" value="<?php echo h($date_from);?>"></div><div class="all-filter"><label>עד תאריך</label><input type="date" name="date_to" value="<?php echo h($date_to);?>"></div><div class="all-filter"><label>סכום מינימלי</label><input type="number" min="0" step="0.01" name="amount_min" value="<?php echo $amount_min===null?'':h($amount_min);?>" placeholder="0"></div><div class="all-filter"><label>סכום מקסימלי</label><input type="number" min="0" step="0.01" name="amount_max" value="<?php echo $amount_max===null?'':h($amount_max);?>" placeholder="ללא הגבלה"></div>
<div class="all-filter"><label>מי הוסיף</label><details class="filter-picker"><summary><span><?php echo h(chosen_name($house_users,$user_id,'הכול'));?></span><i class="fa-solid fa-chevron-down"></i></summary><div class="filter-picker__menu"><button type="button" data-name="user_id" data-value="">הכול</button><?php foreach($house_users as $u):?><button type="button" data-name="user_id" data-value="<?php echo (int)$u['id'];?>"><?php echo h($u['first_name']);?></button><?php endforeach;?></div></details><input type="hidden" name="user_id" value="<?php echo $user_id?:'';?>"></div><div class="all-filter"><label>חודש</label><input type="month" name="month" value="<?php echo h($month);?>"></div><div class="all-filter"><label>סוג אמצעי תשלום</label><details class="filter-picker"><summary><span><?php echo $payment_type? h(tazrim_payment_method_types()[$payment_type]):'הכול';?></span><i class="fa-solid fa-chevron-down"></i></summary><div class="filter-picker__menu"><button type="button" data-name="payment_type" data-value="">הכול</button><?php foreach(tazrim_payment_method_types() as $k=>$v):?><button type="button" data-name="payment_type" data-value="<?php echo h($k);?>"><?php echo h($v);?></button><?php endforeach;?></div></details><input type="hidden" name="payment_type" value="<?php echo h($payment_type);?>"></div></div><div class="all-filter-actions"><button class="all-filter-submit" type="submit"><i class="fa-solid fa-filter"></i>הצג תוצאות</button><a href="all_transactions.php" class="all-filter-reset">ניקוי סינון</a></div></form></div></div></div>
<div class="all-summary"><div><span>נמצאו</span><strong><?php echo count($rows);?> פעולות</strong></div><div class="income"><span>הכנסות</span><strong>+ <?php echo number_format($income,0);?> ₪</strong></div><div class="expense"><span>הוצאות</span><strong>- <?php echo number_format($expense,0);?> ₪</strong></div></div>
<section class="all-results"><?php if(!$rows):?><div class="empty-state text-center"><i class="fa-solid fa-receipt"></i><p>לא נמצאו פעולות שמתאימות לסינון.</p></div><?php endif;?><?php foreach($rows as $row):?><article class="transaction-item all-transaction-row <?php echo h($row['type']);?>" onclick="event.stopPropagation();openAllEdit(JSON.parse(this.dataset.row))" data-row='<?php echo h(json_encode(["id"=>(int)$row["id"],"amount"=>(float)$row["amount"],"description"=>$row["description"],"type"=>$row["type"],"category"=>(int)$row["category"],"payment_method_id"=>$row["payment_method_id"]===null?null:(int)$row["payment_method_id"]],JSON_UNESCAPED_UNICODE));?>'><div class="transaction-info"><div class="cat-icon-wrapper"><i class="fa-solid <?php echo h($row['cat_icon']?:'fa-tag');?>"></i></div><div class="details"><span class="desc"><?php echo h($row['description']);?><?php if($row['user_name']):?><small>(<?php echo h($row['user_name']);?>)</small><?php endif;?></span><span class="date"><?php echo date('d/m/Y',strtotime($row['transaction_date']));?> · <?php echo h($row['category_name']?:'ללא קטגוריה');?><?php if($row['payment_name']):?> <span class="transaction-payment-chip"><i class="fa-solid fa-wallet"></i><?php echo h($row['payment_name']);?></span><?php endif;?></span></div></div><div class="transaction-actions"><div class="transaction-amount"><?php echo $row['type']==='income'?'+':'-';?> <?php echo number_format((float)$row['amount'],2);?> ₪</div><div class="transaction-row-actions"><button type="button" class="transaction-action-pill" title="ערוך פעולה" onclick="event.stopPropagation();openAllEdit(JSON.parse(this.dataset.row))" data-row='<?php echo h(json_encode(["id"=>(int)$row["id"],"amount"=>(float)$row["amount"],"description"=>$row["description"],"type"=>$row["type"],"category"=>(int)$row["category"],"payment_method_id"=>$row["payment_method_id"]===null?null:(int)$row["payment_method_id"]],JSON_UNESCAPED_UNICODE));?>'><i class="fa-solid fa-pen"></i></button><button type="button" class="transaction-action-pill transaction-action-pill--danger" title="מחק פעולה" onclick="event.stopPropagation();deleteAllTransaction(<?php echo (int)$row['id'];?>)"><i class="fa-solid fa-trash-can"></i></button></div></div></article><?php endforeach;?></section>
</div></main></div>
<div id="all-edit-modal" class="modal"><div class="modal-content" style="max-width:450px"><div class="modal-header"><h3>עריכת פעולה</h3><button type="button" onclick="closeAllEdit()" class="close-modal-btn" aria-label="סגור" title="סגור"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div><div class="modal-body"><form id="all-edit-form" class="form-fields-pill"><input type="hidden" name="transaction_id" id="all-edit-id"><input type="hidden" id="all-edit-type"><div class="input-group"><label>תיאור הפעולה</label><div class="input-with-icon"><i class="fa-solid fa-pen"></i><input type="text" name="description" id="all-edit-description" required></div></div><div class="input-group"><label>סכום (₪)</label><div class="input-with-icon"><i class="fa-solid fa-shekel-sign"></i><input type="number" name="amount" id="all-edit-amount" min="0.01" step="0.01" required style="font-size:1.2rem;font-weight:800"></div></div><div class="input-group"><label>קטגוריה</label><div id="all-edit-category-grid"></div><input type="hidden" name="category_id" id="all-edit-category" required></div><div class="input-group"><label>אמצעי תשלום</label><input type="hidden" name="payment_method_id" id="all-edit-payment"><div class="payment-picker" id="all-payment-picker"><button type="button" class="payment-picker__trigger" aria-haspopup="listbox" aria-expanded="false"><span class="payment-picker__value"><i class="fa-solid fa-wallet"></i><span>בחירת אמצעי תשלום</span></span><i class="fa-solid fa-chevron-down"></i></button><div class="payment-picker__menu" role="listbox"></div></div></div><div id="all-edit-msg" style="margin-bottom:15px;font-weight:700;text-align:center;display:none;padding:10px;border-radius:8px"></div><button type="submit" class="btn-primary" id="all-edit-submit" style="margin-top:5px"><i class="fa-solid fa-save"></i> שמור שינויים</button></form></div></div></div>
<script>
function openAllFilters(){document.getElementById('all-filters-modal').style.display='block';}function closeAllFilters(){document.getElementById('all-filters-modal').style.display='none';}
var allCategories=<?php echo json_encode($categories,JSON_UNESCAPED_UNICODE);?>,allPayments=<?php echo json_encode(array_map(function($p){return ['id'=>(int)$p['id'],'name'=>tazrim_payment_method_public_name($p),'type'=>$p['type']];},$payment_methods),JSON_UNESCAPED_UNICODE);?>,allEditType='';
function escAll(v){var d=document.createElement('div');d.textContent=v;return d.innerHTML;}
function initAllPicker(id,input,items,icon){var p=document.getElementById(id),m=p.querySelector('.payment-picker__menu');m.innerHTML=items.map(function(x){return '<button type="button" class="payment-picker__option" data-value="'+x.id+'"><i class="fa-solid '+(x.icon||icon)+'"></i><span>'+escAll(x.name)+'</span><i class="fa-solid fa-check"></i></button>';}).join('');p.querySelector('.payment-picker__trigger').onclick=function(e){e.stopPropagation();p.classList.toggle('open');};m.onclick=function(e){var b=e.target.closest('button');if(!b)return;document.getElementById(input).value=b.dataset.value;p.querySelector('.payment-picker__value span').textContent=b.textContent.trim();p.classList.remove('open');};}
function setAllPicker(id,input,value,items){var x=items.find(function(i){return Number(i.id)===Number(value);});if(x){document.getElementById(input).value=x.id;document.querySelector('#'+id+' .payment-picker__value span').textContent=x.name;}}
function buildAllCategory(type,value){var c=document.getElementById('all-edit-category-grid'),items=allCategories.filter(function(x){return x.type===type;}),sel=items.find(function(x){return Number(x.id)===Number(value);});c.innerHTML='<div class="custom-select-wrapper"><div class="custom-select-trigger"><div class="selected-cat-info"><i class="fa-solid '+(sel&&sel.icon||'fa-list-ul')+'" style="color:var(--main)"></i> <span>'+(sel?escAll(sel.name):'בחירת קטגוריה...')+'</span></div><i class="fa-solid fa-chevron-down"></i></div><div class="custom-select-options">'+items.map(function(x){return '<div class="custom-option" data-value="'+x.id+'"><i class="fa-solid '+(x.icon||'fa-tag')+'"></i> <span>'+escAll(x.name)+'</span></div>';}).join('')+'</div></div>';document.getElementById('all-edit-category').value=sel?sel.id:'';var w=c.firstElementChild;w.querySelector('.custom-select-trigger').onclick=function(e){e.stopPropagation();w.classList.toggle('open');};w.querySelector('.custom-select-options').onclick=function(e){var o=e.target.closest('.custom-option');if(!o)return;document.getElementById('all-edit-category').value=o.dataset.value;w.querySelector('.selected-cat-info').innerHTML=o.innerHTML;w.classList.remove('open');};}
function openAllEdit(row){allEditType=row.type;initAllPicker('all-payment-picker','all-edit-payment',allPayments,'fa-wallet');document.getElementById('all-edit-id').value=row.id;document.getElementById('all-edit-type').value=row.type;document.getElementById('all-edit-description').value=row.description;document.getElementById('all-edit-amount').value=row.amount;buildAllCategory(row.type,row.category);setAllPicker('all-payment-picker','all-edit-payment',row.payment_method_id,allPayments);document.getElementById('all-edit-modal').style.display='block';}
function closeAllEdit(){document.getElementById('all-edit-modal').style.display='none';}
async function deleteAllTransaction(id){if(!await tazrimConfirm({title:'מחיקת פעולה',message:'למחוק את הפעולה לצמיתות?',confirmText:'מחק',cancelText:'ביטול',danger:true}))return;var f=new FormData();f.append('id',id);var d=await fetch('../app/ajax/delete_transaction.php',{method:'POST',body:f}).then(function(r){return r.json();});if(d.status==='success')location.reload();else tazrimAlert({title:'לא הצלחנו למחוק',message:d.message||'נסו שוב'});}
document.getElementById('all-edit-form').addEventListener('submit',async function(e){e.preventDefault();var d=await fetch('../app/ajax/edit_transaction.php',{method:'POST',body:new FormData(this)}).then(function(r){return r.json();});if(d.status==='success')location.reload();else tazrimAlert({title:'לא הצלחנו לעדכן',message:d.message||'נסו שוב'});});
document.querySelectorAll('.filter-picker button').forEach(function(b){b.addEventListener('click',function(){var d=b.closest('details'),n=b.dataset.name;document.querySelector('input[name="'+n+'"]').value=b.dataset.value;d.querySelector('summary span').textContent=b.textContent.trim();d.open=false;});});document.addEventListener('click',function(e){document.querySelectorAll('.filter-picker[open]').forEach(function(d){if(!d.contains(e.target))d.open=false;});document.querySelectorAll('.payment-picker.open').forEach(function(p){if(!p.contains(e.target))p.classList.remove('open');});});
</script></body></html>
